// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "privacy-policy.mdx": () => import("../content/docs/privacy-policy.mdx?collection=docs"), "terms-of-service.mdx": () => import("../content/docs/terms-of-service.mdx?collection=docs"), "getting-started/configuration.mdx": () => import("../content/docs/getting-started/configuration.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/quick-start.mdx": () => import("../content/docs/getting-started/quick-start.mdx?collection=docs"), "reference/api.mdx": () => import("../content/docs/reference/api.mdx?collection=docs"), "reference/changelog.mdx": () => import("../content/docs/reference/changelog.mdx?collection=docs"), "reference/faq.mdx": () => import("../content/docs/reference/faq.mdx?collection=docs"), "guide/analytics.mdx": () => import("../content/docs/guide/analytics.mdx?collection=docs"), "guide/appearance.mdx": () => import("../content/docs/guide/appearance.mdx?collection=docs"), "guide/apple-wallet.mdx": () => import("../content/docs/guide/apple-wallet.mdx?collection=docs"), "guide/blocks.mdx": () => import("../content/docs/guide/blocks.mdx?collection=docs"), "guide/contact-form.mdx": () => import("../content/docs/guide/contact-form.mdx?collection=docs"), "guide/export-import.mdx": () => import("../content/docs/guide/export-import.mdx?collection=docs"), "guide/social-networks.mdx": () => import("../content/docs/guide/social-networks.mdx?collection=docs"), "guide/vcard.mdx": () => import("../content/docs/guide/vcard.mdx?collection=docs"), "self-hosting/cloudflare.mdx": () => import("../content/docs/self-hosting/cloudflare.mdx?collection=docs"), "self-hosting/coolify.mdx": () => import("../content/docs/self-hosting/coolify.mdx?collection=docs"), "self-hosting/custom-domain.mdx": () => import("../content/docs/self-hosting/custom-domain.mdx?collection=docs"), "self-hosting/docker.mdx": () => import("../content/docs/self-hosting/docker.mdx?collection=docs"), "self-hosting/environment-variables.mdx": () => import("../content/docs/self-hosting/environment-variables.mdx?collection=docs"), "self-hosting/railway.mdx": () => import("../content/docs/self-hosting/railway.mdx?collection=docs"), }),
};
export default browserCollections;