export interface ThemePreset {
  name: string;
  label: string;
  cssVars: {
    light: Record<string, string>;
    dark: Record<string, string>;
  };
}

export const themePresets: ThemePreset[] = [
  {
    name: "default",
    label: "Liquid",
    cssVars: {
      light: {
        "--ld-primary": "#091533",
        "--ld-secondary": "#E2E8F0",
        "--ld-accent": "#0FACED",
        "--ld-action": "#091533",
        "--ld-background": "#FFFFFF",
        "--ld-foreground": "#0F172A",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#0F172A",
        "--ld-border": "#E2E8F0",
        "--ld-muted": "#F1F5F9",
        "--ld-muted-foreground": "#586882",
        "--ld-radius": "0.5rem",
      },
      dark: {
        "--ld-primary": "#0FACED",
        "--ld-secondary": "#1E293B",
        "--ld-accent": "#38BDF8",
        "--ld-action": "#38BDF8",
        "--ld-background": "#091533",
        "--ld-foreground": "#F8FAFC",
        "--ld-card": "#0F1D3D",
        "--ld-card-foreground": "#F8FAFC",
        "--ld-border": "#1E293B",
        "--ld-muted": "#1E293B",
        "--ld-muted-foreground": "#94A3B8",
        "--ld-radius": "0.5rem",
      },
    },
  },
  {
    name: "corporate-classic",
    label: "Corporate Classic",
    cssVars: {
      light: {
        "--ld-primary": "#1E3A5F",
        "--ld-secondary": "#E2E8F0",
        "--ld-accent": "#2563EB",
        "--ld-action": "#1E40AF",
        "--ld-background": "#FAFBFC",
        "--ld-foreground": "#1E293B",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#1E293B",
        "--ld-border": "#CBD5E1",
        "--ld-muted": "#F1F5F9",
        "--ld-muted-foreground": "#586882",
        "--ld-radius": "0.375rem",
      },
      dark: {
        "--ld-primary": "#3B82F6",
        "--ld-secondary": "#1E293B",
        "--ld-accent": "#60A5FA",
        "--ld-action": "#60A5FA",
        "--ld-background": "#0F172A",
        "--ld-foreground": "#F1F5F9",
        "--ld-card": "#1E293B",
        "--ld-card-foreground": "#F1F5F9",
        "--ld-border": "#334155",
        "--ld-muted": "#334155",
        "--ld-muted-foreground": "#8899AE",
        "--ld-radius": "0.375rem",
      },
    },
  },
  {
    name: "blood-moon",
    label: "Blood Moon",
    cssVars: {
      light: {
        "--ld-primary": "#B91C1C",
        "--ld-secondary": "#FEE2E2",
        "--ld-accent": "#DC2626",
        "--ld-action": "#991B1B",
        "--ld-background": "#FDF5F5",
        "--ld-foreground": "#1C0505",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#1C0505",
        "--ld-border": "#FECACA",
        "--ld-muted": "#FEF2F2",
        "--ld-muted-foreground": "#7F1D1D",
        "--ld-radius": "0.5rem",
      },
      dark: {
        "--ld-primary": "#EF4444",
        "--ld-secondary": "#1A0505",
        "--ld-accent": "#F87171",
        "--ld-action": "#F87171",
        "--ld-background": "#0C0505",
        "--ld-foreground": "#FEF2F2",
        "--ld-card": "#1A0808",
        "--ld-card-foreground": "#FEF2F2",
        "--ld-border": "#450A0A",
        "--ld-muted": "#1A0808",
        "--ld-muted-foreground": "#FCA5A5",
        "--ld-radius": "0.5rem",
      },
    },
  },
  {
    name: "hacker-terminal",
    label: "Hacker Terminal",
    cssVars: {
      light: {
        "--ld-primary": "#16A34A",
        "--ld-secondary": "#F0FDF4",
        "--ld-accent": "#22C55E",
        "--ld-action": "#15803D",
        "--ld-background": "#FAFDF7",
        "--ld-foreground": "#14532D",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#14532D",
        "--ld-border": "#BBF7D0",
        "--ld-muted": "#F0FDF4",
        "--ld-muted-foreground": "#15803D",
        "--ld-radius": "0rem",
      },
      dark: {
        "--ld-primary": "#00FF41",
        "--ld-secondary": "#0A1A0A",
        "--ld-accent": "#39FF14",
        "--ld-action": "#00FF41",
        "--ld-background": "#0D0208",
        "--ld-foreground": "#00FF41",
        "--ld-card": "#0A1A0A",
        "--ld-card-foreground": "#00FF41",
        "--ld-border": "#003B00",
        "--ld-muted": "#0A1A0A",
        "--ld-muted-foreground": "#00B814",
        "--ld-radius": "0rem",
      },
    },
  },
  {
    name: "shadow-wolf",
    label: "Shadow Wolf",
    cssVars: {
      light: {
        "--ld-primary": "#374151",
        "--ld-secondary": "#E5E7EB",
        "--ld-accent": "#60A5FA",
        "--ld-action": "#1F2937",
        "--ld-background": "#F4F6F9",
        "--ld-foreground": "#111827",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#111827",
        "--ld-border": "#D1D5DB",
        "--ld-muted": "#F3F4F6",
        "--ld-muted-foreground": "#334155",
        "--ld-radius": "0.375rem",
      },
      dark: {
        "--ld-primary": "#94A3B8",
        "--ld-secondary": "#111827",
        "--ld-accent": "#38BDF8",
        "--ld-action": "#38BDF8",
        "--ld-background": "#080E18",
        "--ld-foreground": "#F1F5F9",
        "--ld-card": "#111827",
        "--ld-card-foreground": "#F1F5F9",
        "--ld-border": "#1E293B",
        "--ld-muted": "#111827",
        "--ld-muted-foreground": "#93C5FD",
        "--ld-radius": "0.375rem",
      },
    },
  },
  {
    name: "hellfire",
    label: "Hellfire",
    cssVars: {
      light: {
        "--ld-primary": "#C2410C",
        "--ld-secondary": "#FFF7ED",
        "--ld-accent": "#EA580C",
        "--ld-action": "#9A3412",
        "--ld-background": "#FDFAF6",
        "--ld-foreground": "#1C0A00",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#1C0A00",
        "--ld-border": "#FED7AA",
        "--ld-muted": "#FFF7ED",
        "--ld-muted-foreground": "#7C2D12",
        "--ld-radius": "0.25rem",
      },
      dark: {
        "--ld-primary": "#F97316",
        "--ld-secondary": "#1C1108",
        "--ld-accent": "#FB923C",
        "--ld-action": "#FB923C",
        "--ld-background": "#0D0704",
        "--ld-foreground": "#FFF7ED",
        "--ld-card": "#1C1108",
        "--ld-card-foreground": "#FFF7ED",
        "--ld-border": "#431407",
        "--ld-muted": "#1C1108",
        "--ld-muted-foreground": "#FCA86A",
        "--ld-radius": "0.25rem",
      },
    },
  },
  {
    name: "abyssal",
    label: "Abyssal",
    cssVars: {
      light: {
        "--ld-primary": "#7C3AED",
        "--ld-secondary": "#F5F3FF",
        "--ld-accent": "#8B5CF6",
        "--ld-action": "#6D28D9",
        "--ld-background": "#FAFAFE",
        "--ld-foreground": "#1E1B4B",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#1E1B4B",
        "--ld-border": "#DDD6FE",
        "--ld-muted": "#F5F3FF",
        "--ld-muted-foreground": "#4C1D95",
        "--ld-radius": "0.75rem",
      },
      dark: {
        "--ld-primary": "#A855F7",
        "--ld-secondary": "#130A1F",
        "--ld-accent": "#C084FC",
        "--ld-action": "#C084FC",
        "--ld-background": "#08040F",
        "--ld-foreground": "#F5F3FF",
        "--ld-card": "#130A1F",
        "--ld-card-foreground": "#F5F3FF",
        "--ld-border": "#3B0764",
        "--ld-muted": "#130A1F",
        "--ld-muted-foreground": "#C4B5FD",
        "--ld-radius": "0.75rem",
      },
    },
  },
];
