export interface ThemePreset {
  name: string;
  label: string;
  cssVars: {
    light: Record<string, string>;
    dark: Record<string, string>;
  };
}

export const themePresets: ThemePreset[] = [
  {
    name: "default",
    label: "Liquid",
    cssVars: {
      light: {
        "--ld-primary": "#0FACED",
        "--ld-secondary": "#E2E8F0",
        "--ld-accent": "#38BDF8",
        "--ld-action": "#0284C7",
        "--ld-background": "#FFFFFF",
        "--ld-foreground": "#0F172A",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#0F172A",
        "--ld-border": "#E2E8F0",
        "--ld-muted": "#F1F5F9",
        "--ld-muted-foreground": "#64748B",
        "--ld-radius": "0.5rem",
      },
      dark: {
        "--ld-primary": "#0FACED",
        "--ld-secondary": "#1E293B",
        "--ld-accent": "#38BDF8",
        "--ld-action": "#38BDF8",
        "--ld-background": "#091533",
        "--ld-foreground": "#F8FAFC",
        "--ld-card": "#0F1D3D",
        "--ld-card-foreground": "#F8FAFC",
        "--ld-border": "#1E293B",
        "--ld-muted": "#1E293B",
        "--ld-muted-foreground": "#94A3B8",
        "--ld-radius": "0.5rem",
      },
    },
  },
  {
    name: "corporate-classic",
    label: "Corporate Classic",
    cssVars: {
      light: {
        "--ld-primary": "#1E3A5F",
        "--ld-secondary": "#E2E8F0",
        "--ld-accent": "#2563EB",
        "--ld-action": "#1E40AF",
        "--ld-background": "#FAFBFC",
        "--ld-foreground": "#1E293B",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#1E293B",
        "--ld-border": "#CBD5E1",
        "--ld-muted": "#F1F5F9",
        "--ld-muted-foreground": "#64748B",
        "--ld-radius": "0.375rem",
      },
      dark: {
        "--ld-primary": "#3B82F6",
        "--ld-secondary": "#1E293B",
        "--ld-accent": "#60A5FA",
        "--ld-action": "#60A5FA",
        "--ld-background": "#0F172A",
        "--ld-foreground": "#F1F5F9",
        "--ld-card": "#1E293B",
        "--ld-card-foreground": "#F1F5F9",
        "--ld-border": "#334155",
        "--ld-muted": "#334155",
        "--ld-muted-foreground": "#94A3B8",
        "--ld-radius": "0.375rem",
      },
    },
  },
  {
    name: "corporate-modern",
    label: "Corporate Modern",
    cssVars: {
      light: {
        "--ld-primary": "#0D9488",
        "--ld-secondary": "#F0FDFA",
        "--ld-accent": "#14B8A6",
        "--ld-action": "#0F766E",
        "--ld-background": "#FAFAFA",
        "--ld-foreground": "#18181B",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#18181B",
        "--ld-border": "#E4E4E7",
        "--ld-muted": "#F4F4F5",
        "--ld-muted-foreground": "#71717A",
        "--ld-radius": "0.5rem",
      },
      dark: {
        "--ld-primary": "#2DD4BF",
        "--ld-secondary": "#1C1917",
        "--ld-accent": "#5EEAD4",
        "--ld-action": "#5EEAD4",
        "--ld-background": "#18181B",
        "--ld-foreground": "#FAFAFA",
        "--ld-card": "#27272A",
        "--ld-card-foreground": "#FAFAFA",
        "--ld-border": "#3F3F46",
        "--ld-muted": "#3F3F46",
        "--ld-muted-foreground": "#A1A1AA",
        "--ld-radius": "0.5rem",
      },
    },
  },
  {
    name: "hacker-terminal",
    label: "Hacker Terminal",
    cssVars: {
      light: {
        "--ld-primary": "#16A34A",
        "--ld-secondary": "#F0FDF4",
        "--ld-accent": "#22C55E",
        "--ld-action": "#15803D",
        "--ld-background": "#FAFDF7",
        "--ld-foreground": "#14532D",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#14532D",
        "--ld-border": "#BBF7D0",
        "--ld-muted": "#F0FDF4",
        "--ld-muted-foreground": "#4ADE80",
        "--ld-radius": "0rem",
      },
      dark: {
        "--ld-primary": "#00FF41",
        "--ld-secondary": "#0A1A0A",
        "--ld-accent": "#39FF14",
        "--ld-action": "#00FF41",
        "--ld-background": "#0D0208",
        "--ld-foreground": "#00FF41",
        "--ld-card": "#0A1A0A",
        "--ld-card-foreground": "#00FF41",
        "--ld-border": "#003B00",
        "--ld-muted": "#0A1A0A",
        "--ld-muted-foreground": "#008F11",
        "--ld-radius": "0rem",
      },
    },
  },
  {
    name: "neon-cyber",
    label: "Neon Cyber",
    cssVars: {
      light: {
        "--ld-primary": "#7C3AED",
        "--ld-secondary": "#F5F3FF",
        "--ld-accent": "#06B6D4",
        "--ld-action": "#6D28D9",
        "--ld-background": "#FAFAFE",
        "--ld-foreground": "#1E1B4B",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#1E1B4B",
        "--ld-border": "#DDD6FE",
        "--ld-muted": "#F5F3FF",
        "--ld-muted-foreground": "#7C3AED",
        "--ld-radius": "0.75rem",
      },
      dark: {
        "--ld-primary": "#A855F7",
        "--ld-secondary": "#1A0A2E",
        "--ld-accent": "#22D3EE",
        "--ld-action": "#C084FC",
        "--ld-background": "#0A0118",
        "--ld-foreground": "#E0D4FD",
        "--ld-card": "#1A0A2E",
        "--ld-card-foreground": "#E0D4FD",
        "--ld-border": "#3B0764",
        "--ld-muted": "#1A0A2E",
        "--ld-muted-foreground": "#8B5CF6",
        "--ld-radius": "0.75rem",
      },
    },
  },
  {
    name: "furry-pastel",
    label: "Furry Pastel",
    cssVars: {
      light: {
        "--ld-primary": "#EC4899",
        "--ld-secondary": "#FDF2F8",
        "--ld-accent": "#A855F7",
        "--ld-action": "#DB2777",
        "--ld-background": "#FFFBFE",
        "--ld-foreground": "#4A1942",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#4A1942",
        "--ld-border": "#FBCFE8",
        "--ld-muted": "#FDF2F8",
        "--ld-muted-foreground": "#BE185D",
        "--ld-radius": "1rem",
      },
      dark: {
        "--ld-primary": "#F472B6",
        "--ld-secondary": "#2D1228",
        "--ld-accent": "#C084FC",
        "--ld-action": "#F9A8D4",
        "--ld-background": "#1A0A18",
        "--ld-foreground": "#FDF2F8",
        "--ld-card": "#2D1228",
        "--ld-card-foreground": "#FDF2F8",
        "--ld-border": "#4A1942",
        "--ld-muted": "#2D1228",
        "--ld-muted-foreground": "#EC4899",
        "--ld-radius": "1rem",
      },
    },
  },
  {
    name: "furry-bold",
    label: "Furry Bold",
    cssVars: {
      light: {
        "--ld-primary": "#EA580C",
        "--ld-secondary": "#FFF7ED",
        "--ld-accent": "#0D9488",
        "--ld-action": "#C2410C",
        "--ld-background": "#FFFCF5",
        "--ld-foreground": "#431407",
        "--ld-card": "#FFFFFF",
        "--ld-card-foreground": "#431407",
        "--ld-border": "#FED7AA",
        "--ld-muted": "#FFF7ED",
        "--ld-muted-foreground": "#C2410C",
        "--ld-radius": "0.75rem",
      },
      dark: {
        "--ld-primary": "#FB923C",
        "--ld-secondary": "#1C1108",
        "--ld-accent": "#2DD4BF",
        "--ld-action": "#FDBA74",
        "--ld-background": "#120C04",
        "--ld-foreground": "#FFF7ED",
        "--ld-card": "#1C1108",
        "--ld-card-foreground": "#FFF7ED",
        "--ld-border": "#431407",
        "--ld-muted": "#1C1108",
        "--ld-muted-foreground": "#EA580C",
        "--ld-radius": "0.75rem",
      },
    },
  },
];
