export interface ThemePreset {
	name: string;
	label: string;
	description: string;
	cssVars: {
		light: Record<string, string>;
		dark: Record<string, string>;
	};
}

export const themePresets: ThemePreset[] = [
	{
		name: "default",
		label: "Classic",
		description: "Clean and minimal with bright backgrounds",
		cssVars: {
			light: {
				"--ld-primary": "#091533",
				"--ld-secondary": "#E2E8F0",
				"--ld-accent": "#0FACED",
				"--ld-background": "#FFFFFF",
				"--ld-foreground": "#0F172A",
				"--ld-card": "#FFFFFF",
				"--ld-card-foreground": "#0F172A",
				"--ld-border": "#E2E8F0",
				"--ld-muted": "#F1F5F9",
				"--ld-muted-foreground": "#586882",
			},
			dark: {
				"--ld-primary": "#0FACED",
				"--ld-secondary": "#1E293B",
				"--ld-accent": "#38BDF8",
				"--ld-background": "#091533",
				"--ld-foreground": "#F8FAFC",
				"--ld-card": "#0F1D3D",
				"--ld-card-foreground": "#F8FAFC",
				"--ld-border": "#1E293B",
				"--ld-muted": "#1E293B",
				"--ld-muted-foreground": "#94A3B8",
			},
		},
	},
	{
		name: "dark",
		label: "Graphite",
		description: "Sleek dark theme with subtle contrasts",
		cssVars: {
			light: {
				"--ld-primary": "#374151",
				"--ld-secondary": "#E5E7EB",
				"--ld-accent": "#60A5FA",
				"--ld-background": "#F4F6F9",
				"--ld-foreground": "#111827",
				"--ld-card": "#FFFFFF",
				"--ld-card-foreground": "#111827",
				"--ld-border": "#D1D5DB",
				"--ld-muted": "#F3F4F6",
				"--ld-muted-foreground": "#334155",
			},
			dark: {
				"--ld-primary": "#94A3B8",
				"--ld-secondary": "#111827",
				"--ld-accent": "#38BDF8",
				"--ld-background": "#080E18",
				"--ld-foreground": "#F1F5F9",
				"--ld-card": "#111827",
				"--ld-card-foreground": "#F1F5F9",
				"--ld-border": "#1E293B",
				"--ld-muted": "#111827",
				"--ld-muted-foreground": "#93C5FD",
			},
		},
	},
	{
		name: "ocean-blue",
		label: "Ocean Blue",
		description: "Deep blues inspired by the ocean",
		cssVars: {
			light: {
				"--ld-primary": "#1E3A5F",
				"--ld-secondary": "#E0F2FE",
				"--ld-accent": "#0EA5E9",
				"--ld-background": "#F0F9FF",
				"--ld-foreground": "#0C4A6E",
				"--ld-card": "#FFFFFF",
				"--ld-card-foreground": "#0C4A6E",
				"--ld-border": "#BAE6FD",
				"--ld-muted": "#E0F2FE",
				"--ld-muted-foreground": "#0369A1",
			},
			dark: {
				"--ld-primary": "#38BDF8",
				"--ld-secondary": "#082F49",
				"--ld-accent": "#7DD3FC",
				"--ld-background": "#0C1929",
				"--ld-foreground": "#E0F2FE",
				"--ld-card": "#0A2540",
				"--ld-card-foreground": "#E0F2FE",
				"--ld-border": "#164E63",
				"--ld-muted": "#0A2540",
				"--ld-muted-foreground": "#67E8F9",
			},
		},
	},
	{
		name: "sunset",
		label: "Sunset",
		description: "Warm oranges and golden tones",
		cssVars: {
			light: {
				"--ld-primary": "#C2410C",
				"--ld-secondary": "#FFF7ED",
				"--ld-accent": "#F97316",
				"--ld-background": "#FFFBF5",
				"--ld-foreground": "#431407",
				"--ld-card": "#FFFFFF",
				"--ld-card-foreground": "#431407",
				"--ld-border": "#FED7AA",
				"--ld-muted": "#FFF7ED",
				"--ld-muted-foreground": "#9A3412",
			},
			dark: {
				"--ld-primary": "#FB923C",
				"--ld-secondary": "#1C1108",
				"--ld-accent": "#FDBA74",
				"--ld-background": "#1A0F05",
				"--ld-foreground": "#FFF7ED",
				"--ld-card": "#271A0C",
				"--ld-card-foreground": "#FFF7ED",
				"--ld-border": "#431407",
				"--ld-muted": "#271A0C",
				"--ld-muted-foreground": "#FCA86A",
			},
		},
	},
	{
		name: "forest",
		label: "Forest",
		description: "Natural greens with earthy warmth",
		cssVars: {
			light: {
				"--ld-primary": "#166534",
				"--ld-secondary": "#DCFCE7",
				"--ld-accent": "#22C55E",
				"--ld-background": "#F0FDF4",
				"--ld-foreground": "#14532D",
				"--ld-card": "#FFFFFF",
				"--ld-card-foreground": "#14532D",
				"--ld-border": "#BBF7D0",
				"--ld-muted": "#F0FDF4",
				"--ld-muted-foreground": "#15803D",
			},
			dark: {
				"--ld-primary": "#4ADE80",
				"--ld-secondary": "#0A1A0F",
				"--ld-accent": "#86EFAC",
				"--ld-background": "#061208",
				"--ld-foreground": "#DCFCE7",
				"--ld-card": "#0A1A0F",
				"--ld-card-foreground": "#DCFCE7",
				"--ld-border": "#14532D",
				"--ld-muted": "#0A1A0F",
				"--ld-muted-foreground": "#86EFAC",
			},
		},
	},
	{
		name: "minimal",
		label: "Minimal",
		description: "Ultra-clean with monochrome palette",
		cssVars: {
			light: {
				"--ld-primary": "#18181B",
				"--ld-secondary": "#F4F4F5",
				"--ld-accent": "#71717A",
				"--ld-background": "#FFFFFF",
				"--ld-foreground": "#09090B",
				"--ld-card": "#FAFAFA",
				"--ld-card-foreground": "#09090B",
				"--ld-border": "#E4E4E7",
				"--ld-muted": "#F4F4F5",
				"--ld-muted-foreground": "#65656D",
			},
			dark: {
				"--ld-primary": "#E4E4E7",
				"--ld-secondary": "#18181B",
				"--ld-accent": "#A1A1AA",
				"--ld-background": "#09090B",
				"--ld-foreground": "#FAFAFA",
				"--ld-card": "#18181B",
				"--ld-card-foreground": "#FAFAFA",
				"--ld-border": "#27272A",
				"--ld-muted": "#18181B",
				"--ld-muted-foreground": "#A1A1AA",
			},
		},
	},
	{
		name: "corporate-classic",
		label: "Corporate Classic",
		description: "Professional blue tones for business",
		cssVars: {
			light: {
				"--ld-primary": "#1E3A5F",
				"--ld-secondary": "#E2E8F0",
				"--ld-accent": "#2563EB",
				"--ld-background": "#FAFBFC",
				"--ld-foreground": "#1E293B",
				"--ld-card": "#FFFFFF",
				"--ld-card-foreground": "#1E293B",
				"--ld-border": "#CBD5E1",
				"--ld-muted": "#F1F5F9",
				"--ld-muted-foreground": "#586882",
			},
			dark: {
				"--ld-primary": "#3B82F6",
				"--ld-secondary": "#1E293B",
				"--ld-accent": "#60A5FA",
				"--ld-background": "#0F172A",
				"--ld-foreground": "#F1F5F9",
				"--ld-card": "#1E293B",
				"--ld-card-foreground": "#F1F5F9",
				"--ld-border": "#334155",
				"--ld-muted": "#334155",
				"--ld-muted-foreground": "#A8B5C4",
			},
		},
	},
	{
		name: "blood-moon",
		label: "Blood Moon",
		description: "Bold crimson with dramatic contrasts",
		cssVars: {
			light: {
				"--ld-primary": "#B91C1C",
				"--ld-secondary": "#FEE2E2",
				"--ld-accent": "#DC2626",
				"--ld-background": "#FDF5F5",
				"--ld-foreground": "#1C0505",
				"--ld-card": "#FFFFFF",
				"--ld-card-foreground": "#1C0505",
				"--ld-border": "#FECACA",
				"--ld-muted": "#FEF2F2",
				"--ld-muted-foreground": "#7F1D1D",
			},
			dark: {
				"--ld-primary": "#EF4444",
				"--ld-secondary": "#1A0505",
				"--ld-accent": "#F87171",
				"--ld-background": "#0C0505",
				"--ld-foreground": "#FEF2F2",
				"--ld-card": "#1A0808",
				"--ld-card-foreground": "#FEF2F2",
				"--ld-border": "#450A0A",
				"--ld-muted": "#1A0808",
				"--ld-muted-foreground": "#FCA5A5",
			},
		},
	},
	{
		name: "hacker-terminal",
		label: "Hacker Terminal",
		description: "Matrix-inspired neon green on black",
		cssVars: {
			light: {
				"--ld-primary": "#15803D",
				"--ld-secondary": "#F0FDF4",
				"--ld-accent": "#22C55E",
				"--ld-background": "#FAFDF7",
				"--ld-foreground": "#14532D",
				"--ld-card": "#FFFFFF",
				"--ld-card-foreground": "#14532D",
				"--ld-border": "#BBF7D0",
				"--ld-muted": "#F0FDF4",
				"--ld-muted-foreground": "#15803D",
			},
			dark: {
				"--ld-primary": "#00FF41",
				"--ld-secondary": "#0A1A0A",
				"--ld-accent": "#39FF14",
				"--ld-background": "#0D0208",
				"--ld-foreground": "#B8FFD0",
				"--ld-card": "#0A1A0A",
				"--ld-card-foreground": "#B8FFD0",
				"--ld-border": "#003B00",
				"--ld-muted": "#0A1A0A",
				"--ld-muted-foreground": "#66FF85",
			},
		},
	},
	{
		name: "hellfire",
		label: "Hellfire",
		description: "Fiery orange with blazing intensity",
		cssVars: {
			light: {
				"--ld-primary": "#C2410C",
				"--ld-secondary": "#FFF7ED",
				"--ld-accent": "#EA580C",
				"--ld-background": "#FDFAF6",
				"--ld-foreground": "#1C0A00",
				"--ld-card": "#FFFFFF",
				"--ld-card-foreground": "#1C0A00",
				"--ld-border": "#FED7AA",
				"--ld-muted": "#FFF7ED",
				"--ld-muted-foreground": "#7C2D12",
			},
			dark: {
				"--ld-primary": "#F97316",
				"--ld-secondary": "#1C1108",
				"--ld-accent": "#FB923C",
				"--ld-background": "#0D0704",
				"--ld-foreground": "#FFF7ED",
				"--ld-card": "#1C1108",
				"--ld-card-foreground": "#FFF7ED",
				"--ld-border": "#431407",
				"--ld-muted": "#1C1108",
				"--ld-muted-foreground": "#FCA86A",
			},
		},
	},
	{
		name: "abyssal",
		label: "Abyssal",
		description: "Deep purple with mysterious depth",
		cssVars: {
			light: {
				"--ld-primary": "#7C3AED",
				"--ld-secondary": "#F5F3FF",
				"--ld-accent": "#8B5CF6",
				"--ld-background": "#FAFAFE",
				"--ld-foreground": "#1E1B4B",
				"--ld-card": "#FFFFFF",
				"--ld-card-foreground": "#1E1B4B",
				"--ld-border": "#DDD6FE",
				"--ld-muted": "#F5F3FF",
				"--ld-muted-foreground": "#4C1D95",
			},
			dark: {
				"--ld-primary": "#A855F7",
				"--ld-secondary": "#130A1F",
				"--ld-accent": "#C084FC",
				"--ld-background": "#08040F",
				"--ld-foreground": "#F5F3FF",
				"--ld-card": "#130A1F",
				"--ld-card-foreground": "#F5F3FF",
				"--ld-border": "#3B0764",
				"--ld-muted": "#130A1F",
				"--ld-muted-foreground": "#C4B5FD",
			},
		},
	},
];
