import { z } from "zod";

export const UpdateVcardSchema = z.object({
  firstName: z.string().max(100).optional(),
  lastName: z.string().max(100).optional(),
  prefix: z.string().max(20).optional(),
  suffix: z.string().max(20).optional(),
  nickname: z.string().max(100).optional(),
  birthday: z.string().max(20).optional(),
  photo: z.string().max(2000).optional(),
  organization: z.string().max(200).optional(),
  title: z.string().max(200).optional(),
  role: z.string().max(200).optional(),
  department: z.string().max(200).optional(),
  email: z.string().email().max(200).optional().or(z.literal("")),
  emailWork: z.string().email().max(200).optional().or(z.literal("")),
  phone: z.string().max(30).optional(),
  phoneWork: z.string().max(30).optional(),
  phoneMobile: z.string().max(30).optional(),
  fax: z.string().max(30).optional(),
  addressStreet: z.string().max(300).optional(),
  addressCity: z.string().max(100).optional(),
  addressState: z.string().max(100).optional(),
  addressZip: z.string().max(20).optional(),
  addressCountry: z.string().max(100).optional(),
  addressWorkStreet: z.string().max(300).optional(),
  addressWorkCity: z.string().max(100).optional(),
  addressWorkState: z.string().max(100).optional(),
  addressWorkZip: z.string().max(20).optional(),
  addressWorkCountry: z.string().max(100).optional(),
  website: z.string().max(2000).optional(),
  websiteWork: z.string().max(2000).optional(),
  socialTwitter: z.string().max(200).optional(),
  socialLinkedin: z.string().max(200).optional(),
  socialGithub: z.string().max(200).optional(),
  socialInstagram: z.string().max(200).optional(),
  socialFacebook: z.string().max(200).optional(),
  socialYoutube: z.string().max(200).optional(),
  notes: z.string().max(5000).optional(),
});

export type UpdateVcardInput = z.infer<typeof UpdateVcardSchema>;
