export const placeholderSettings: Record<string, string> = {
  profileName: "John Doe",
  profileBio: "Digital creator & full-stack developer. Building cool things on the internet.",
  profileImage: "",
  contactEmail: "john@example.com",
  theme: "midnight-glass",
  themeMode: "dark",
  contactEnabled: "false",
  accentColor: "#0FACED",
  backgroundColor: "#091533",
  textColor: "rgba(255,255,255,0.95)",
  verifiedBadge: "false",
  brandEnabled: "true",
  brandName: "",
  brandLogo: "",
  brandFavicon: "",
  socialLinks: "[]",
  metaTitle: "LinkDen",
  metaDescription: "Your personal link-in-bio page",
  metaImage: "",
  customCss: "",
  customHead: "",
  captchaSiteKey: "",
  captchaSecretKey: "",
  captchaType: "none",
};
